_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
BATCH_SIZE:
    value: 32
EPISODES:
    value: 500000
EPSILON:
    value: 1
EPSILON_DECAY:
    value: 1000000
EPSILON_MIN:
    value: 0.01
FRAME_REPEAT:
    value: 1
GAME_NAME:
    value: BreakoutNoFrameskip-v4
GAMMA:
    value: 0.99
LEARNING_RATE:
    value: 0.0001
LIVES:
    value: 5
PRETRAINED_MODEL_PATH:
    value: models/
RECORD_VIDEOS:
    value: true
REPLAY_MEMORY_SIZE:
    value: 1000000
SAVE_FREQUENCY:
    value: 10000
START_TRAINING_AT_STEP:
    value: 100000
TARGET_NET_UPDATE_FREQUENCY:
    value: 10000
TRAINING_FREQUENCY:
    value: 4
USE_PRETRAINED:
    value: false
USE_WANDB:
    value: true
VIDEO_RECORD_FREQUENCY:
    value: 100
WANDB_ENTITY:
    value: neuroori
WANDB_PROJECT:
    value: DQN
